name: formularios_front
description: "A Flutter Clean Architecture project for Intelicity demands."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gates_microapp_flutter:
    git:
      url: https://github.com/inteli-city/gates_authentication.git
      ref: dev
      path: packages/gates_microapp_flutter
  badges: ^3.1.2
  dio: ^5.4.2+1
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  uno: ^1.1.9
  logger: ^2.2.0
  provider: ^6.1.2
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_modular: ^6.3.3
  dropdown_button2: ^2.3.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
flutter_intl:
  enabled: true